# Generated by Django 5.2.1 on 2025-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("INR", "INR"),
                            ("GBP", "GBP"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("external_id", models.CharField(max_length=50, unique=True)),
                (
                    "last_modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("owner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("ProductA", "Product A"),
                            ("ProductB", "Product B"),
                            ("ProductC", "Product C"),
                        ],
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "wording_full_name",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("wording_name", models.CharField(max_length=80)),
                ("wording_url", models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
