# Generated by Django 5.2.1 on 2025-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsonformapp", "0002_alter_column_column_name_alter_row_row_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
