# Generated by Django 5.2.1 on 2025-05-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsonformapp", "0003_form_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="row",
            name="row_order",
        ),
        migrations.AddField(
            model_name="field",
            name="data_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="db_column_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="field",
            name="is_Required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="field",
            name="max_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
