# Generated by Django 5.2.1 on 2025-05-28 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsonformapp", "0004_remove_row_row_order_field_data_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="table_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="row",
            name="row_order",
            field=models.IntegerField(
                default=1,
                help_text="Column order in the row (1 to 3)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
