# Generated by Django 5.2.1 on 2025-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsonformapp", "0005_form_table_name_row_row_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_fee", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "agency_commission",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("bank_account", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=80)),
                ("product_code", models.CharField(max_length=5)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "Indian Rupee"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "product_family",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto Insurance"),
                            ("HEALTH", "Health Insurance"),
                            ("TRAVEL", "Travel Insurance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "assurance_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bsb", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cancellation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_annual", models.BooleanField(default=False)),
                ("parameters", models.TextField(blank=True, null=True)),
                (
                    "platform_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("section_definition", models.TextField(blank=True, null=True)),
                ("wording_url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
