# Generated by Django 5.2.1 on 2025-06-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jsonformapp", "0007_wording"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Wording",
        ),
    ]
