# Generated by Django 5.2.1 on 2025-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=80)),
                ("product_code", models.CharField(max_length=5, unique=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("INR", "Indian Rupee"), ("USD", "US Dollar")],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_annual", models.BooleanField(default=False)),
                (
                    "platform_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "admin_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "agency_commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "assurance_charge",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "cancellation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bsb", models.CharField(blank=True, max_length=255, null=True)),
                ("parameters", models.TextField(blank=True, null=True)),
                (
                    "product_family",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Health", "Health"),
                            ("Travel", "Travel"),
                            ("Life", "Life"),
                            ("Motor", "Motor"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("section_definition", models.TextField(blank=True, null=True)),
                ("wording_url", models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
